### PR TITLE
adding FUNDING.yml

### PR DESCRIPTION
**Pull request by julien51**
## Changes

As an Open Source project, we @unlock-protocol believe Wallet connect should have a `FUNDING.yml` file which lets people make donations if they use the software, like we do!

This pull requests adds donations thru an [Unlock](https://unlock-protocol.com/) lock. Locks are smart contract which let people become members by purchasing a key. The key itself is a non fungible token: 🗝 . 

You can make a donation (and purchase a key!) on [this page](https://donate.unlock-protocol.com/?thank-you=VGhhbmtzIGEgbG90IGZvciBzdXBwb3J0aW5nIG91ciB3b3JrIQ==&config=eyJwZXJzaXN0ZW50Q2hlY2tvdXQiOnRydWUsImljb24iOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vV2FsbGV0Q29ubmVjdC93YWxsZXRjb25uZWN0LWFzc2V0cy9tYXN0ZXIvcG5nL3dhbGxldGNvbm5lY3QtYmFubmVyLnBuZyIsImNhbGxUb0FjdGlvbiI6eyJkZWZhdWx0IjoiU3VwcG9ydCB0aGUgV2FsbGV0IENvbm5lY3QgdGVhbSBhbmQgdW5sb2NrIHlvdXIgbWVtYmVyc2hpcCB0b2RheSEgXG5cbllvdSBjYW4gbWFrZSBhIGRvbmF0aW9uIGJ5IHB1cmNoYXNpbmcgYSBrZXkgdXNpbmcgeW91ciBFdGhlcmV1bSB3YWxsZXQuIFRoZSBrZXkgaXMgYSBub24gZnVuZ2libGUgdG9rZW4gd2hpY2ggcmVwcmVzZW50cyB5b3VyIG1lbWJlcnNoaXAuICJ9LCJsb2NrcyI6eyIweDhhRkE0RmVmZjhCNTY3NkJjZDc2MzQxYWQxYkEzMDM4MjQ1RjI1OTYiOnsibmFtZSI6IldhbGxldCBDb25uZWN0IE1lbWJlcnMifX19&) (linked inside of the FUNDING.yml file)

This specific lock is at [`0x8aFA4Feff8B5676Bcd76341ad1bA3038245F2596`](https://etherscan.io/address/0x8aFA4Feff8B5676Bcd76341ad1bA3038245F2596). The curent key price is 1 DAI. I currently own the lock but I'll happily transfer its ownership to you if you can send me an address ;) After that, you will be able to _update the price_, the name and withdraw the funds from the [Unlock](https://github.com/unlock-protocol/unlock/) dashboard.

Keys are valid for 1 month and there can be an infinite number of keys.

PS: if you want to create your own FUNDING.yml link you can easily [with this application](https://donate.unlock-protocol.com/generate.html).

### CODE REVIEW

**Comment by localethereumMichael** [comment]
I'm not sure I understand the purpose of the lock. Why not just have a plain ETH address for donations, instead of a smart contract with a seemingly unnecessary ERC721 reward?

**Comment by julien51** [comment]
I do think that the ERC721 is actually critical to donation. Many NGO for examples will give you a pin when you make a donation... some will give you a tote bag, etc. It's all done to show your support beyond just actually "paying".
Similarly most "donation" platforms will show badges for the projects that a given user/organization supports.

Additionally the lock could also be used to actually grant access to some features/content which would be just for members. An example of that is for example some kind of "launch party" where only the members can get a free drink, or even a website where they can access some unique features... etc.

**Comment by pedrouid** [comment]
LGTM and once we get WalletConnect integrated into Unlock even better 👌

**Comment by julien51** [comment]
> LGTM and once we get WalletConnect integrated into Unlock even better 👌

Yes!

**Pull request merged**
