### PR TITLE
AlgorandProvider #877

### PR DESCRIPTION
**Pull request by scholtz**
> Creating a release? Please use the [Release PR Template](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/.github/pr_template_release.md) instead.

## Description

AlgorandProvider

## Type of change

- [x] Chore (non-breaking change that addresses non-functional tasks, or code quality improvements)
- [x] New feature (non-breaking change which adds functionality)

## How has this been tested?

I did run npm run check in root folder.

## Fixes/Resolves (Optional)

#877 

## Checklist

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Additional Information (Optional)

https://github.com/ChainAgnostic/namespaces/pull/72/files

### CODE REVIEW

**Comment by scholtz** [comment]
also related to https://github.com/WalletConnect/walletconnect-monorepo/issues/2538

**Comment by scholtz** [comment]
Wallet Connect integration to AWallet: https://github.com/scholtz/wallet/pull/47 Public review of the pull request is here: https://awallet-git-feature-wc2-scholtz.vercel.app/

At the moment must use the https://www.npmjs.com/package/universal-provider-with-algorand  .. Waiting for this PR to be merged so that we can use official package.

**Comment by scholtz** [comment]
Also, if you like to see it in action: https://youtu.be/NQvLfQqQk8E

**Review by ganchoradkov — COMMENTED** [review]
Hey @scholtz thanks for the PR! 💯 
Would it be possible to add a test case with an example usage of `algo_signTxn`? Would be helpful to people wishing to use the provider with `algorand`

**Comment by glitch-txs** [comment]
closing due to inactivity, feel free to reopen with the requested additions. Thanks!

**Pull request closed without merging**
