### PR TITLE
Add mobile-linking support

### PR DESCRIPTION
**Pull request by pedrouid**
- [x] Detect browser and OS environment
- [x] Display deep linking for mobile
- [ ] Display single deep link for Android
- [x] Display multiple deep link for iOS
- [ ] Register deep link on core client
- [ ] Trigger deep link on signing requests

### CODE REVIEW

**Comment by rhlsthrm** [comment]
Hey @brunobar79! It looks like you're making some progress on this. Is there a way to test the deep linking feature right now? I'm trying to get something up and running that makes use of this feature. Is there a wallet app that supports this right now? CC @pedrouid.

**Comment by rhlsthrm** [comment]
Now that this is merged is there a way to test the functionality @pedrouid @brunobar79 ?

**Comment by pycckuu** [comment]
Yes, please, let me know too.

**Comment by pycckuu** [comment]
More specifically, universal links

**Pull request merged**
