### PR TITLE
Add trust wallet to mobile registry

### PR DESCRIPTION
**Pull request by hewigovens**
The functionality will be available in later iOS build

### CODE REVIEW

**Comment by pedrouid** [comment]
What date is this expected to hit production?

**Comment by hewigovens** [comment]
Tbh I don’t know, it depends on Apple review 😓

**Comment by pedrouid** [comment]
Just ping me when it's ready and I can publish this in a couple of mins

**Comment by hewigovens** [comment]
@pedrouid can you try latest Trust iOS, it supports wc universal link now

ezgif com-video-to-gif

**Pull request merged**
