### PR TITLE
ExchangeKey react-native cryptography lib

### PR DESCRIPTION
**Pull request by georgiemathews**

### CODE REVIEW

**Comment by pedrouid** [comment]
Hi @georgiemathews, just tested your PR with `walletconnect-developer-app` on `debug` branch and I'm getting an empty ArrayBuffer from the method `decryptWithPrivateKey()`. This happens during the `_handleKeyUpdate()` on the `core` package.

**Comment by pedrouid** [comment]
PS - To test it a agaisnt the example dapp, check out the deploy preview available at https://debug-exchange-key--walletconnect-example.netlify.com

**Comment by georgiemathews** [comment]
> PS - To test it a against the example dapp, check out the deploy preview available at https://debug-exchange-key--walletconnect-example.netlify.com

@pedrouid, could you give me some direction on how I could test this out, earlier, I just created a new connection with the url from https://debug-exchange-key--walletconnect-example.netlify.com and ran all of the cryptolib functions to encrypt and decrypt a message. That worked fine. Would love to debug this further if you let me know what you did to test.

**Comment by pedrouid** [comment]
I ran the [walletconnect-developer-app](https://github.com/WalletConnect/walletconnect-developer-app) repo on [debug](https://github.com/WalletConnect/walletconnect-developer-app/tree/debug) branch on my iPhone (you could also do it from Android). 

Then I started a connection with the url https://debug-exchange-key--walletconnect-example.netlify.com. Once I approved the connection from my phone, it threw an error `Failed to execute key update` from [here](https://github.com/WalletConnect/walletconnect-monorepo/blob/18f91b1fd6eb6e38223b7ba9fb1a3cebcf550865/packages/core/src/index.ts#L1107).

I debugged the issue and found that the decrypted message was an empty ArrayBuffer ([here](https://github.com/WalletConnect/walletconnect-monorepo/blob/18f91b1fd6eb6e38223b7ba9fb1a3cebcf550865/packages/core/src/index.ts#L1073)). I've left the `console.log` calls on the `debug` branch of the react-native project, so you will be able to inspect yourself on [L1094](https://github.com/WalletConnect/walletconnect-developer-app/blob/c6c0ab0f6daf7d7a46d9ec30175878b0fce29fd0/src/walletconnect/core.ts#L1094) the empty arrayBuffer.

**Comment by georgiemathews** [comment]
@pedrouid tried to reproduce this error, still having trouble getting the handlekeyupdate error, cloned the debug branch, built on my physical device and scanned qr code from the deploy preview, tried to send a transaction, could not replicate this error.

**Comment by pedrouid** [comment]
> @pedrouid tried to reproduce this error, still having trouble getting the handlekeyupdate error, cloned the debug branch, built on my physical device and scanned qr code from the deploy preview, tried to send a transaction, could not replicate this error.

Only saw this now, I will give it a try again

**Comment by pedrouid** [comment]
Hi @georgiemathews, I have tried it again and I'm still getting the same issue, here is the step-by-step to reproduce.

1. `git clone https://github.com/WalletConnect/walletconnect-developer-app.git`
2. `cd walletconnect-developer-app`
3. `git checkout debug`
4. `npm install`
5. `npm run start`
6. `open walletconnectdeveloperapp.xcodeproj`
7. Press "Run" on XCode with iPhone connected
8. Open Deploy Preview (https://debug-exchange-key--walletconnect-example.netlify.com/)
9. Scan QR Code with Developer App on iPhone
10. Error returned in browser "Failed to execute key update"

The error is thrown always on the same line from the core package where `this.cryptoLib.decryptWithPrivateKey` returns an empty ArrayBuffer on [L1072](https://github.com/WalletConnect/walletconnect-monorepo/blob/a7e7d24747dcb698fdb25a1a4b5a4ff445333a2a/packages/core/src/index.ts#L1072)

Let me know if you are able to reproduce this error

**Comment by georgiemathews** [comment]
@pedrouid, still debugging, but I tried a handful of times using the exact steps you listed to reproduce and couldn't get the error, checked that cryptolib was correctly generating the keypairs and didn't find anything erroneous. I'll keep you updated!

**Pull request closed without merging**
