### PR TITLE
fix:modal types

### PR DESCRIPTION
**Pull request by ganchoradkov**
## Description

- fixed `@walletconnect/modal` types to use `---wcm` prefix instead of `---w3m` that was removed in previous versions
- updated it to latest

## Type of change

- [x] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Draft PR (breaking/non-breaking change which needs more work for having a proper functionality _[Mark this PR as ready to review only when completely ready]_)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?
dogfooding

## Checklist

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by svenvoskamp — APPROVED** [review]

**Comment by chybisov** [comment]
Please also fix documentation https://docs.walletconnect.com/web3modal/javascript/theming

**Comment by bkrem** [comment]
> Please also fix documentation [docs.walletconnect.com/web3modal/javascript/theming](https://docs.walletconnect.com/web3modal/javascript/theming)

@chybisov the relevant documentation for the more basic WalletConnectModal (which is separate from Web3Modal) lives here: https://docs.walletconnect.com/advanced/walletconnectmodal/theming

**Comment by chybisov** [comment]
> > Please also fix documentation [docs.walletconnect.com/web3modal/javascript/theming](https://docs.walletconnect.com/web3modal/javascript/theming)
> 
> 
> 
> @chybisov the relevant documentation for the more basic WalletConnectModal (which is separate from Web3Modal) lives here: https://docs.walletconnect.com/advanced/walletconnectmodal/theming

Oh, thank you, it wasn't that obvious 😄

**Comment by bkrem** [comment]
All good, please do raise it with us if you find incorrect documentation nonetheless! 🙏

**Pull request merged**
