### PR TITLE
v1.7.2

### PR DESCRIPTION
**Pull request by pedrouid**
- replace bn.js with BigInt
- replace query-string with URLSearchParams

### CODE REVIEW

**Comment by pedrouid** [comment]
@TimDaub you can see below a comparison between v1.7.1 and v1.7.2-rc.0 which includes both PRs you have submitted and we can see substantial bundle reduction 💪  Thanks a lot for your contributions!

Only thing missing now is testing agaisnt react-native applications to support as low as v0.60 potentially

Screenshot 2022-01-11 at 12 10 06

**Comment by TimDaub** [comment]
wow this is super cool! thanks for sharing @pedrouid

**Comment by xzilja** [comment]
@pedrouid Tested these cases with react native running on hermes engine

```
  console.log(parseInt('1010', 10))
  console.log(parseInt('0x1F7', 16))
  console.log(BigInt(9007199254740991).toString())
  console.log(BigInt(9007199254740991).toString(16))
  console.log(new URLSearchParams('q=URLUtils.searchParams&topic=api').toString())
```

`BigInt` - is not supported at all, related issue https://github.com/facebook/hermes/issues/510
`parseInt` - Is fine as expected
`URLSearchParams` - Doesn't error, but it returns empty result to me, where as I expected `q=URLUtils.searchParams&topic=api` (which happens in browser)

So overall this whole change would be breaking rn

**Comment by pedrouid** [comment]
That's a shame! We will need to develop separate target libraries to support these changes for NodeJS and Browser while still using the current dependencies for React-Native

**Pull request closed without merging**
