### PR TITLE
fix: send appId to socket url

### PR DESCRIPTION
**Pull request by ignaciosantise**
## Description

Send bundleId or packageName to socket connection url for react-native

## Type of change

- [ ] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Draft PR (breaking/non-breaking change which needs more work for having a proper functionality _[Mark this PR as ready to review only when completely ready]_)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?

Tested locally on Mobile Sample App

## Fixes/Resolves (Optional)

Cloud allowlist validation issues in mobile devices

## Checklist

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Additional Information (Optional)
Related PR: https://github.com/WalletConnect/walletconnect-utils/pull/205

### CODE REVIEW

**Review by Cali93 — APPROVED** [review]
LGTM but it'd be great to add at least some unit tests.

**Comment by ignaciosantise** [comment]
@Cali93 tests to isAndroid/isIos functions? or where?

**Comment by Cali93** [comment]
@Cali93 tests to isAndroid/isIos functions? or where?

Yes just to make sure it doesn't break eg if `Platform` has a value that we don't expect.
If it's too big of a lift and you already manually tested this we can have a follow up PR for the tests.

**Comment by ignaciosantise** [comment]
~@Cali93 @ganchoradkov any idea on how to capture the `Unauthorized: origin not allowed` on a test?~
~I thought subscribing to relayer.provider.on('payload') and add an `expect` there~

done

**Comment by Cali93** [comment]
Thanks a lot for adding the tests 🙏

**Review by ganchoradkov — APPROVED** [review]

**Pull request merged**
