### PR TITLE
feat: Adds QuickNode support to `getRpcUrl`

### PR DESCRIPTION
**Pull request by felipecsl**
## Summary

* Rename `infuraNetworks` to `networks`
* Create `QuickNodeConfig`
* Create `getQuickNodeRpcUrl`
* Use QuickNode URL if `quicknodeConfig` is set, otherwise use Infura URL if `infuraId` is set
* Wrote some unit tests

### CODE REVIEW

**Review by DiegoSPB — APPROVED** [review]
LGTM

**Comment by abunsen** [comment]
Hi @pedrouid is there a guide for contributing or getting a build passing here?

**Comment by abunsen** [comment]
cc @sbc64

**Comment by ganchoradkov** [comment]
closing as stale

**Pull request closed without merging**
