### PR TITLE
tx.to empty string ENS error potential fix

### PR DESCRIPTION
**Pull request by mubarakone**
test for potential fix: https://github.com/ethers-io/ethers.js/issues/2750#issue-1156133556

### CODE REVIEW

**Comment by mubarakone** [comment]
@kyokosdream

**Comment by kyokosdream** [comment]
@mubarakone I'm trying to fork the repo and install the custom fork using npm but I'm not having any success. I think the problem has to do with the monorepo structure and the use of scoped packages. Not sure how to proceed.

**Comment by kyokosdream** [comment]
Could we just get this request merged as soon as possible? It's proved exceedingly difficult to install a forked version of the code given the monorepo structure, me and @mubarakone have spent many hours attempting to do so. Contract deployment is currently broken with WalletConnect anyway so this change can't hurt any existing users. 

I would recommend just changing this single line:
OLD
 `to: typeof txData.to === "undefined" ? "" : sanitizeHex(txData.to)`
NEW
 `to: typeof txData.to === "undefined" ? null : sanitizeHex(txData.to)`

**Comment by mubarakone** [comment]
> Could we just get this request merged as soon as possible? It's proved exceedingly difficult to install a forked version of the code given the monorepo structure, me and @mubarakone have spent many hours attempting to do so. Contract deployment is currently broken with WalletConnect anyway so this change can't hurt any existing users.
> 
> I would recommend just changing this single line: OLD `to: typeof txData.to === "undefined" ? "" : sanitizeHex(txData.to)` NEW `to: typeof txData.to === "undefined" ? null : sanitizeHex(txData.to)`

Will do

**Review by mubarakone — COMMENTED** [review]
https://github.com/WalletConnect/walletconnect-monorepo/pull/974#issuecomment-1109046968

**Comment by kyokosdream** [comment]
The changes we've made don't comply with `@walletconnect/types` unfortunately. We may need to change the `null` to `undefined`.

**Comment by pedrouid** [comment]
@kyokosdream @mubarakone I have published v1.7.8 with these changes

**Comment by kyokosdream** [comment]
@pedrouid You're a legend thanks for assisting us on this so quickly. I will test today.

**Comment by mubarakone** [comment]
@pedrouid Thanks for the merge! We worked really hard to solve this issue. 
If you don't mind, I applied for a Javscript position, and I figured volunteering for you guys would be a good way to get a refferal. I can solve more issues and submit more PRs if I can continue to be apart of your team. Let me know how that sounds! Thanks once again.

**Pull request merged**
