### PR TITLE
feat: added a mobile detect package and implemented

### PR DESCRIPTION
**Pull request by JonathanConn**
## Description
Added a [package](https://www.npmjs.com/package/mobile-detect) for mobile OS detection in `utils`

## Type of change

- [ ] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Draft PR (breaking/non-breaking change which needs more work for having a proper functionality _[Mark this PR as ready to review only when completely ready]_)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?
Testing locally using sym links

## Checklist

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Additional Information
I would like to publish a canary for further testing before merge

### CODE REVIEW

**Comment by JonathanConn** [comment]
Adding local unit tests now

**Review by bkrem — APPROVED** [review]

**Comment by bkrem** [comment]
@JonathanConn Canary published as: `@walletconnect/utils@2.8.0-a7f3975e`

**Comment by bkrem** [comment]
@JonathanConn @ignaciosantise what's the status on this?

**Comment by bkrem** [comment]
Superseded by https://github.com/WalletConnect/walletconnect-monorepo/pull/2724

**Pull request closed without merging**
