### PR TITLE
feat:add eip5792 methods as optional methods

### PR DESCRIPTION
**Pull request by KannuSingh**
Adding EIP-5792 methods on the list of optional RPC methods. These method will become part of session proposal request to wallet.
This will enable wallet supporting EIP-5792 allowing dapps to use it after session is successfully approved by the user.

### CODE REVIEW

**Review by tomiir — COMMENTED** [review]
LGTM but would wait for an approval from @ganchoradkov

**Review by arein — COMMENTED** [review]
triple-checking: are these all just the optional methods?

**Comment by KannuSingh** [comment]
IMO Yes, it all optional methods. 
And if made required_methods then wallet need to support all those, else session can't be established.

**Review by ganchoradkov — APPROVED** [review]
Awesome 🔥

**Pull request merged**
