### PR TITLE
feat: Implement Eventemitter#removeAllListener.

### LINKED ISSUE #1761: Implement removeAllListeners
**Is your feature request related to a problem? Please describe.**
I want to be able to remove all listeners at once. 

**Describe the solution you'd like**
https://nodejs.dev/en/api/v19/events/#emitterremovealllistenerseventname

**Describe alternatives you've considered**
Making it manually for every event :)

### PR DESCRIPTION
**Pull request by antondalgren**
# Description

Make it possible to remove all listeners for the sign client. Currently it is only possible to remove one listener at a time by passing the event it listens on and the callback function.

Resolves #1761

## How Has This Been Tested?
Locally in my own app, it works smoothly.

## Due Dilligence

* [ ] Breaking change
* [x] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Comment by antondalgren** [comment]
@0xAsimetriq Could you pop an eye on this please? :)

**Review by bkrem — APPROVED** [review]

**Review by ganchoradkov — APPROVED** [review]

**Comment by antondalgren** [comment]
Sorry for the spam 😅 ☝️

**Review by ganchoradkov — APPROVED** [review]

**Comment by antondalgren** [comment]
Can we try and get this into a release this week? :)

**Comment by bkrem** [comment]
> Can we try and get this into a release this week? :)

@antondalgren shipped as part of https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.1.5 🎁

**Pull request merged**
