### PR TITLE
Fix approveSession data

### PR DESCRIPTION
**Pull request by jdkanani**
Approve session like - 
```
approveSession(["0x123...", ... ])
```

or need to change `getSessionStatus` in `walletconnect/walletconnect`

### CODE REVIEW

**Comment by pedrouid** [comment]
I see what you mean but it's better to update `getSessionStatus` to make it consistent through encryptionPayloads

**Comment by pedrouid** [comment]
Actually I just realised that is not necessary to expose the variable approved as well, because it's not used by the bridge at all

**Comment by jdkanani** [comment]
There are multiple inconsistencies. Maybe we should fix the standard of data passing between client-bridge-rn and then follow it.

**Comment by pedrouid** [comment]
That's what Im doing right now

**Comment by pedrouid** [comment]
duplicate #36

**Pull request closed without merging**
