### PR TITLE
Change RPC JSON response success condition

### LINKED ISSUE #930: (REACT-NATIVE) JSON RPC response format is invalid
I tried to use the `sendCustomRequest `and the method is `wallet_switchEthereumChain` to request to switch the network on the metamask mobile, when I press switch network button on the metamask app it return me this error on my dApp `JSON RPC response format is invalid`. Here is my sample code

```
 const requestSwitchNetwork = async () => {
    try {
      await connector.sendCustomRequest({
        id: 0,
        jsonrpc: '2.0',
        method: 'wallet_switchEthereumChain',
        params: [ { chainId: ethers.utils.hexlify(CHAIN_ID) } ],
      });
    } catch (error) {
      // Always getting error
      console.log(error);
    }
  };
```
I tried this on the metamask API playground and it works fine.
https://metamask.github.io/api-playground/api-documentation/#wallet_switchEthereumChain

### PR DESCRIPTION
**Pull request by poriyaalarsamvelraja**
Fixes  #930

According to[ RPC JSON format 2.0 ](https://www.jsonrpc.org/specification#response_object)

```
This member MUST NOT exist if there was an error invoking the method.
```

The condition `if(payload.result)` would fail if the result is `null` which is true for many success cases.

for example for [wallet_switchEthereumChain](https://docs.metamask.io/guide/rpc-api.html#wallet-switchethereumchain)

### CODE REVIEW

**Comment by pedrouid** [comment]
Duplicate of #977

**Comment by pedrouid** [comment]
My bad! It's not a duplicate

**Comment by poriyaalarsamvelraja** [comment]
Thanks @pedrouid

**Comment by Birdland998** [comment]
I can't install @walletconnect/web3-provider how ti fix it please help @pedrouid 

Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! 
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! exited with error code: 1

**Comment by rightrevsamvelraja** [comment]
@Birdland998 

https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

**Comment by poriyaalarsamvelraja** [comment]
@Birdland998 

https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

**Comment by Birdland998** [comment]
it's work thank you @poriyaalarsamvelraja  @poriyaalarsamvelraja

**Pull request merged**
