### PR TITLE
V0.6.0

### PR DESCRIPTION
**Pull request by pedrouid**
Requires walletconnect/py-walletconnect-bridge#33

### CODE REVIEW

**Comment by jdkanani** [comment]
This looks good. @pedrouid check `rollup` branch.

**Comment by pedrouid** [comment]
Cool! @jdkanani do you want to include the `rollup` branch changes on the `v0.6.0` pr?

**Comment by jdkanani** [comment]
@pedrouid done! https://github.com/WalletConnect/walletconnect-monorepo/pull/7/

**Comment by pedrouid** [comment]
Ahah I did the same thing at #8

**Comment by pedrouid** [comment]
Alright all merged and branches are in sync!

**Pull request merged**
