### PR TITLE
feat: validate topic exists

### PR DESCRIPTION
**Pull request by HarryET**
## Description

Validates that the topic is the same in the webhook payload that would be sent to echo-server

## Type of change

- [x] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Draft PR (breaking/non-breaking change which needs more work for having a proper functionality _[Mark this PR as ready to review only when completely ready]_)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?
Adds new checks to test

## Checklist

- [x] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by arein — APPROVED** [review]
Did you test this?

**Comment by HarryET** [comment]
> Did you test this?

Will test again locally now before merge

**Comment by HarryET** [comment]
@arein looks like the webhook test dosen't give the payload back, needs some changes there

**Comment by arein** [comment]
Cool. What's the payload it returns? You can just make the changes

**Pull request merged**
