### PR TITLE
Add imToken wallet deeplink

### PR DESCRIPTION
**Pull request by sapjax**
Add imToken wallet deeplink

### CODE REVIEW

**Comment by pedrouid** [comment]
What date is this expected to hit production?

**Comment by sapjax** [comment]
> What date is this expected to hit production?

If everything is ok, the new version of imToken will be released In the next two weeks.

**Comment by pedrouid** [comment]
Great! Ping me again in this PR and I will be able to publish it right after

**Comment by sapjax** [comment]
@pedrouid 
~We had released our new version 2.5.8  https://token.im/download.
I think you can merge this PR to the main branch now, Thanks a lot!~
I just saw the https://github.com/WalletConnect/walletconnect-monorepo/pull/305 release PR,  ignore me.

**Pull request merged**
