### PR TITLE
feat: added Tezos to universal provider

### PR DESCRIPTION
**Pull request by dianasavvatina**
## Description

Tezos is added to UniversalProvider based on other blockchains in UniversalProvider

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How has this been tested?

Used in example

## Checklist

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dianasavvatina** [comment]
@ganchoradkov, could you please take a look at this one?
It's required for PR #5357 and for PR [#696](https://github.com/reown-com/web-examples/pull/696) in web-examples

**Review by ganchoradkov — APPROVED** [review]
Sorry for the delay in the review 🙏 thank you for adding! 💯

**Comment by ganchoradkov** [comment]
hey @dianasavvatina could you update your PR with base so I can merge 🙏

**Comment by ganchoradkov** [comment]
@dianasavvatina seems like prettier is failing, could you run `npm run prettier` please 🙏

**Pull request merged**
