### PR TITLE
feat: move eth_signTypedData_v4 to REQUIRED

### PR DESCRIPTION
**Pull request by DJXin-cn**
> Creating a release? Please use the [Release PR Template](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/.github/pr_template_release.md) instead.

## Description

Please include a brief summary of the change.

## Type of change

- [ ] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Draft PR (breaking/non-breaking change which needs more work for having a proper functionality _[Mark this PR as ready to review only when completely ready]_)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?
Dapp

## Checklist

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ganchoradkov** [comment]
Hey @DJXin-cn, thanks for the PR. Could you give a bit of context why you feel `eth_signTypedData_v4` should be moved to required? Aren't wallets that support it handle it correctly as optional?

**Comment by DJXin-cn** [comment]
Yes, I've tested some wallets, but Bitkeep and TokenPocket don't support it as optional, so I wonder if it can be moved to REQUIRED

**Comment by ganchoradkov** [comment]
> Yes, I've tested some wallets, but Bitkeep and TokenPocket don't support it as optional, so I wonder if it can be moved to REQUIRED

I understand. In this case, please raise the issue with Bitkeep & TokenPocket as it must be addressed by them. The method being proposed as optional is valid CAIP-25 usage.  Adding it as required would cause widespread incompatibility issues with all wallets that do not support the method.

**Comment by DJXin-cn** [comment]
ok, thanks

**Pull request closed without merging**
